[workspace]
resolver = "2"

members = [
    "common",
    "dino",
    "flappy",
    "inkspill",
    "snake",
    "space-invaders",
    "tetris",
    "twenty-48",
]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
