name: Build and Test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: rui314/setup-mold@v1
        with:
          make-default: false
      - uses: actions/checkout@v3
      - name: Link
        run: sudo ln -s /usr/local/bin/mold /usr/bin/mold
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
